### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by ollybowman** [chefsplate/groove-to-helpscout-migration-tool#3]
Thanks for this very useful tool, saved me a lot of hassle.

I'm getting the following error on one ticket transfer though. 

```
=== Starting page 19 of 20 (1159 total tickets, 116 total pages) ===
Approximate ETA: TBD
Groove message #5565904794 (ticket #1115): Attachment cadeau.gif found (8934 bytes). Uploading to HelpScout...
Groove message #9035958440 (ticket #1108): Attachment ACE image3.jpg found (8147952 bytes). Uploading to HelpScout...


  [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                
  Type error: Argument 4 passed to HelpScout\ApiClient::getErrorMessage() must be of the type array, null given, called in /home/vagran  
  t/helpscout/groove-to-helpscout-migration-tool/vendor/helpscout/api/src/HelpScout/ApiClient.php on line 724     
```

I can't really find a reference in the logs to the ticket number though, how would I go about doing this.

**Comment by davidchchang** [comment]
Hi @ollybowman, thanks for your message.

I ran into the same error before, and this usually happens when uploading attachments greater than 8 MB in size. Although I read in the documentation that their API supports attachments of up to 10 MB, we found out this was not the case in reality. 

Here is HelpScout's reply when I reached out to them before about this issue:

> I spoke with one of our API engineers and through some testing, we found that though the file may be less than 10MB, the payload request was more. This is because of the padding added by the base64 encoding. I'm investigating methods within PHP to check the request file size before sending it in order to give you a warning before hitting the server. If that road proves successful, it unfortunately probably wouldn't make it into a release in the near future.

It looks like the issue still hasn't been addressed yet. In the meantime, there are a couple of workarounds: 
- one possibility is throwing an exception if the file is greater than 8 MB in size (e.g. changing this line in the code: https://github.com/chefsplate/groove-to-helpscout-migration-tool/blob/master/app/Console/Commands/Processors/TicketProcessor.php#L262) and then re-running
  `php artisan sync-tickets <ticket #>`
- the other possibility is you can remove the problematic attachment or upload to a different service and link to it from a new message (which is what I do for attachments greater than 10 MB in size).

Hope that helps!
